title: "Forster and Partners LLP"
description: "Chartered Professional Accountants — Toronto, Ontario"
baseurl: "/website"
url: "https://oliviaan-dev.github.io"
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
